name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Synthesize CloudFormation template
      run: cdk synth

    - name: Diff with deployed stack
      run: cdk diff

    outputs:
      cdk_synth_output: ${{ steps.cdk-synth.outputs.stack-artifact-id }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CDK
      run: npm install -g aws-cdk

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Bootstrap CDK (if needed)
      run: cdk bootstrap

    - name: Deploy CDK stack
      run: cdk deploy --all --require-approval never
