name: CDK Deploy (main Branch)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: 3.x

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # - name: Export environment variables
      #   run: |
      #     echo "EMAIL_SUBSCRIPTION_ENDPOINT=${{ vars.EMAIL_SUBSCRIPTION_ENDPOINT }}" >> $GITHUB_ENV
      #     echo "FILE_UPLOAD_BUCKET=${{ vars.FILE_UPLOAD_BUCKET }}" >> $GITHUB_ENV

      - name: Install CDK dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Deploy CDK stack
        run: cdk deploy --all --require-approval never
